### ISSUE TITLE
Make setenforce 0 optional

### ISSUE THREAD

**Issue by elyezer** [Katello/katello-deploy#113]
Setenforce should be 1 by default and 0 if an option is specified. This because working with enforcing is the expected behaviour.

**Comment by omaciel** [comment]
Pretty please?

**Comment by stbenjam** [comment]
@jlsherrill has a PR to make it enforcing all the time, but there's some outstanding issues I think:
   https://github.com/Katello/katello-deploy/pull/101

**Comment by elyezer** [comment]
The #101 got merged, what about closing this?

**Comment by stbenjam** [comment]
Sure, let's close it, it's resolved.
