### ISSUE TITLE
Several issues deploying katello-deploy on Centos 7

### ISSUE THREAD

**Issue by bcorner13** [Katello/katello-deploy#118]
I have not been able to install via katello-deploy on Centos 7.  I have been able to get rid of most of the errors. 
Here is my initial setup.

Installed Centos 7 via Parallels ( on my MAC 10.10.2 OS X )
2 core
4GB RAM
128GB
Manual setup
opted for 500MB /boot
server with gui installation choice
added FQDN to /etc/hosts

During install I received an error during the katello-install steps

yum install ruby git

mkdir /repository
cd /repository
git clone https://github.com/Katello/katello-deploy
cd katello-deploy

useradd foreman
useradd uucp
useradd tomcat
After the directory is created by the rpm executed
chown -R foreman:foreman /usr/share/foreman
semanage port -a -t http_port_t -p tcp 53
./setup.rb --os centos7 —skipinstaller
katello-installer

**ERRORS:**
[root@katello katello-deploy]# grep ERROR /var/log/katello-installer/katello-installer.log 
[ INFO 2015-02-08 13:59:04 main]  # log_level:        The desired logging level. Options are: CRITICAL, ERROR, WARNING, INFO, DEBUG,
[ERROR 2015-02-08 14:05:13 main]  /usr/share/foreman/script/foreman-config      -k ssl_ca_file -v '/etc/foreman/proxy_ca.pem'      -k ssl_certificate -v '/etc/foreman/client_cert.pem'      -k ssl_priv_key -v '/etc/foreman/client_key.pem' returned 1 instead of one of [0]
[ERROR 2015-02-08 14:05:13 main]  /Stage[main]/Certs::Foreman/Exec[foreman_certs_config]/returns: change from notrun to 0 failed: /usr/share/foreman/script/foreman-config      -k ssl_ca_file -v '/etc/foreman/proxy_ca.pem'      -k ssl_certificate -v '/etc/foreman/client_cert.pem'      -k ssl_priv_key -v '/etc/foreman/client_key.pem' returned 1 instead of one of [0]
[ERROR 2015-02-08 14:05:22 main]  /Stage[main]/Foreman_proxy::Register/Foreman_smartproxy[katello.<doman>.com]: Could not evaluate: Could not load data from https://katello.<domain>.com
[ERROR 2015-02-08 14:05:25 main] Repeating errors encountered during run:
[ERROR 2015-02-08 14:05:25 main]  /usr/share/foreman/script/foreman-config      -k ssl_ca_file -v '/etc/foreman/proxy_ca.pem'      -k ssl_certificate -v '/etc/foreman/client_cert.pem'      -k ssl_priv_key -v '/etc/foreman/client_key.pem' returned 1 instead of one of [0]
[ERROR 2015-02-08 14:05:25 main]  /Stage[main]/Certs::Foreman/Exec[foreman_certs_config]/returns: change from notrun to 0 failed: /usr/share/foreman/script/foreman-config      -k ssl_ca_file -v '/etc/foreman/proxy_ca.pem'      -k ssl_certificate -v '/etc/foreman/client_cert.pem'      -k ssl_priv_key -v '/etc/foreman/client_key.pem' returned 1 instead of one of [0]
[ERROR 2015-02-08 14:05:25 main]  /Stage[main]/Foreman_proxy::Register/Foreman_smartproxy[katello.<domain>.com]: Could not evaluate: Could not load data from https://katello.<domain>.com

**Comment by stbenjam** [comment]
This is installing nightly, which is unfortunately broken due to http://projects.theforeman.org/issues/9288.  Try installing 2.1 instead.  (`--version 2.1`)

**Comment by bbuckingham** [comment]
@stbenjam, This looks a lot like errors I also get on nightly & katello 2.1 using RHEL7.  I've mentioned it to @ehelms as well.

**Comment by stbenjam** [comment]
This specific error is pretty generic and happens whenever something bad happens early in the installation. 

You'll certainly get these errors on nightly due to the current sprockets/bastion problem, which is what I'm sure is what's **probably** happening for @bcorner13.   On Katello 2.1 is a different story...  A `foreman-debug` would help if you see it.

@bcorner13  Anywho, thanks for report! :smile: It's not specifically katello-deploy so I'll close this - if you see errors on 2.1, or nightly after #9288 is fixed, please use the bug trucker: http://projects.theforeman.org/projects/katello/issues/new or feel free find us on IRC.  More info on the support section here http://www.katello.org/community/index.html

**Comment by bcorner13** [comment]
I was about to say… I started with 2.0 and found out that some of the Centos7 fixes were only being rolled into 2.1.  So I tried 2.1 and received similar results.  So executing on the nightly was my last try.

**Comment by stbenjam** [comment]
Nightly is definitely broken but 2.1 is a different story, `foreman-debug` and an issue on the bug tracker would help, we don't really use this github repo for installer issue.

**Comment by ehelms** [comment]
@bcorner13 There is an issue related to this http://projects.theforeman.org/issues/9243 that may or may not be the problem you are seeing. Sending us a foreman-debug output or looking through your /var/log/katello-installer.log for 'ERROR' and seeing if its issue would help us. As @stbenjam mentioned, there have been a number of other errors that creeped up and have prevented me from tackling the aforementioned issue (if it is indeed the same one you are seeing.)
