### ISSUE TITLE
VM Vagrant centos-develop does not startup successfully

### ISSUE THREAD

**Issue by komanna** [Katello/katello-deploy#143]
Git-Version: af6015b6dbc169dc2516a4ace15e205ca65ac39b
Can anyone reproduce this Error?
http://pastebin.com/B6UU5dHZ

**Comment by ehelms** [comment]
This issue has been fixed in the git-repository but hasn't propogated to our repositories yet. You can clone (https://github.com/Katello/katello-installer) into the katello-deploy directory and it will use this instead of the RPM.

**Comment by komanna** [comment]
As you said, i just copied https://github.com/Katello/katello-installer as a directory into the katello-installer directory and ran it again => came up nicely.
Do you know when you will merge?

**Comment by ehelms** [comment]
This should be in the official nightly repositories now.
