### ISSUE TITLE
Changing CentOS SCLO repository

### ISSUE THREAD

**Issue by abrianceau** [Katello/katello-deploy#223]
When using ./setup.rb, the repository of CentOS SCLO is not good (running RHEL 7.2).

Wrong URL used : http://mirror.centos.org/centos/7Server/sclo/x86_64/rh/repodata/repomd.xml

Good URL that should be used : http://mirror.centos.org/centos/7/sclo/x86_64/rh/repodata/repomd.xml

The $releasever is "7Server" instead of "7" under CentOS.

How can we fix it ? Or maybe can we you SC from Red Hat ? (www.softwarecollections.org)

**Comment by abrianceau** [comment]
Edit : After editing the repo manually (s/$releasever/7/g), I have a lot of yum depedencies not satisfied : 
sclo-ror42-rubygem(activemodel) < 5
sclo-ror42-rubygem-activerecord < 1:5.0.0
sclo-ror42-rubygem(mime-types) >= 1.16
sclo-ror42-rubygem(concurrent-ruby) >= 1.0
sclo-ror42-rubygem(activerecord) >= 4.0.0
sclo-ror42-rubygem-activerecord >= 2.2.2
sclo-ror42-rubygem(polyglot)
sclo-ror42-rubygem(railties) >= 3.1
sclo-ror42-rubygem(railties) < 5.0
sclo-ror42-rubygem(actionpack) < 5
sclo-ror42-rubygem(railties) >= 3.1.0
sclo-ror42-rubygem(activerecord)
sclo-ror42-rubygem(rails) >= 3.0.7
sclo-ror42-rubygem(nokogiri) >= 1.3.0
sclo-ror42-rubygem(sprockets-rails) >= 2.3.3
sclo-ror42-rubygem-builder
sclo-ror42-rubygem(multi_json) >= 1.8.4
sclo-ror42-rubygem(sprockets) >= 3
sclo-ror42-rubygem(activerecord) >= 4.0.0
sclo-ror42-rubygem(rack)
sclo-ror42-rubygem(activerecord) < 5
sclo-ror42-rubygem(rails) >= 3.1
sclo-ror42-rubygem(activesupport) >= 2.3.14
sclo-ror42-rubygem(rails) >= 4.2.5.1
sclo-ror42-rubygem(turbolinks) >= 2.5
sclo-ror42-rubygem(activemodel) >= 4.0
sclo-ror42-rubygem(activerecord) < 5
sclo-ror42-rubygem(railties) >= 4.0
sclo-ror42-rubygem(nokogiri) < 1.7.0
sclo-ror42-rubygem(i18n) >= 0.5.0
sclo-ror42-rubygem(nokogiri) >= 1.4.1
sclo-ror42-rubygem(concurrent-ruby) < 2.0
sclo-ror42-rubygem-activerecord >= 3.2.0
sclo-ror42-rubygem(railties) >= 4.0.0
sclo-ror42-rubygem(nokogiri) >= 1.5.11
sclo-ror42-runtime
sclo-ror42-rubygem(railties) < 5.1
sclo-ror42-rubygem(concurrent-ruby) >= 1.0.0
sclo-ror42-rubygem(sprockets-rails) < 3
sclo-ror42-rubygem(activerecord) >= 2.3.2
sclo-ror42-rubygem(multi_json) >= 1.10
sclo-ror42-rubygem(concurrent-ruby) < 1.1.0
sclo-ror42-rubygem(railties) >= 4.2.0
sclo-ror42-rubygem(activesupport) >= 3.0.10
sclo-ror42-rubygem(turbolinks) < 3.0
sclo-ror42-rubygem(railties) < 5
sclo-ror42-rubygem(activemodel) < 5
sclo-ror42-rubygem(sprockets)
sclo-ror42-rubygem(multi_json) < 2
sclo-ror42-rubygem-activerecord >= 1:3.1.0
sclo-ror42-rubygem(multi_json)
sclo-ror42-rubygem(builder)
sclo-ror42-rubygem(sprockets) < 4
sclo-ror42-rubygem(i18n) >= 0.7
sclo-ror42-rubygem(activesupport)
sclo-ror42-rubygem(nokogiri) >= 1.6.0
sclo-ror42-rubygem(sinatra)
sclo-ror42-rubygem(activemodel) >= 4.0.1
sclo-ror42-rubygem(i18n) < 1
sclo-ror42-rubygem(nokogiri) < 2.0
sclo-ror42-rubygem(tilt)
sclo-ror42-rubygem(activerecord) >= 4.0
sclo-ror42-rubygem(rails) < 4.2.7
sclo-ror42-rubygem(actionpack) >= 4.0.0

Is it possible that a dev or a tester can handle installation on RHEL 7.2 ? Or do I need to be on 7.1 or 6 ?

**Comment by ekohl** [comment]
Also reported as http://projects.theforeman.org/issues/15008 so it appears this isn't limited to Katello.

**Comment by abrianceau** [comment]
But manual install of Katello 2.4 is OK on my RHEL 7.2 :

yum -y  --disablerepo="*" --enablerepo=rhel-7-server-rpms install yum-utils wget
yum-config-manager --disable "*"
yum-config-manager --enable rhel-7-server-rpms
yum-config-manager --enable rhel-7-server-optional-rpms
yum-config-manager --enable rhel-7-server-extras-rpms
yum -y localinstall http://fedorapeople.org/groups/katello/releases/yum/2.4/katello/RHEL/7Server/x86_64/katello-repos-latest.rpm
yum -y localinstall http://yum.theforeman.org/releases/1.10/el7/x86_64/foreman-release.rpm
yum -y localinstall http://yum.puppetlabs.com/puppetlabs-release-el-7.noarch.rpm
yum -y localinstall http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
yum -y install foreman-release-scl
# Here I had dependencies issues (rubygem-rake etc.), I don't know why but my rhel-7-server-extras was disabled...
yum-config-manager --enable rhel-7-server-extras-rpms
yum -y install katello
echo "$IP $HOSTNAME" >> /etc/hosts
katello-installer

**Comment by ekohl** [comment]
I think that's the difference between nightly and the released version: nightly uses RoR 4.2 which isn't in RHSCL but only in SCLo.

**Comment by stbenjam** [comment]
Indeed, if you want to use katello-deploy, you can give it a particular version to use (see ./setup.rb --help), otherwise it defaults to nightly.

**Comment by ehelms** [comment]
@abrianceau based on the issue presented and the CentOS fix I am going to close this as resolved. Please re-open if you hit any further issues, thanks.
