### ISSUE TITLE
Libvirt: centos-devel fails during mount

### ISSUE THREAD

**Issue by daviddavis** [Katello/katello-deploy#30]
For the libvirt centos-devel setup, Vagrant fails before provisioning because it can't mount the directory. This only seems to happen with the newer versions of Vagrant (1.4.3, 1.5.1) and vagrant-libvirt (0.0.15).

**Comment by ehelms** [comment]
@daviddavis is this still an issue or can we close?

**Comment by daviddavis** [comment]
I haven't tested it out but we really don't use nfs with katello-deploy so closing.
