### ISSUE TITLE
Yum dependency error with vagrant up centos on wheezy/sid

### ISSUE THREAD

**Issue by jhagberg** [Katello/katello-deploy#48]
--> Processing Dependency: python(abi) = 2.7 for package: python-requests-2.2.1-1.fc19.noarch
--> Finished Dependency Resolution
Error: Package: python-requests-2.2.1-1.fc19.noarch (katello-pulp)
           Requires: python(abi) = 2.7
           Installed: python-2.6.6-52.el6.x86_64 (@updates)
               python(abi) = 2.6
           Available: python-2.6.6-51.el6.x86_64 (base)
               python(abi) = 2.6

**Comment by ehelms** [comment]
Closing due to age -- if this is still an issue please re-open with new details, thanks.
